# Site settings
highlighter: rouge
title: "-[|]- Box and Whisker"
email: whisker@boxnwhis.kr
description: > # this means to ignore newlines until "baseurl:"
  Official homepage of Box and Whisker
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://boxnwhis.kr"
timezone: UTC
paginate: 10
encoding: utf-8

# Build settings
markdown: kramdown

# Navigation
navigation:
- url: /index.html
  text: Home
- url: /service.html
  text: Service
- url: /company.html
  text: Company
- url: /contact.html
  text: Contact

exclude: ["*.pynb"]

